In [51]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.neighbors import KNeighborsClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix, plot_confusion_matrix

1. In markdown, describe KNN in your own words.

KNN is a supervised learning algorithm used for classification and regression problem. KNN means k-Nearest Neighbors. KNN used in the variety of applications such as finance, healthcare, political science, handwriting detection, image recognition and video recognition. In Credit ratings, financial institutes will predict the credit rating of customers. In loan disbursement, banking institutes will predict whether the loan is safe or risky. In political science, classifying potential voters in two classes will vote or won’t vote.The training phase of K-nearest neighbor classification is much faster compared to other classification algorithms. There is no need to train a model for generalization, That is why KNN is known as the simple and instance-based learning algorithm. KNN can be useful in case of nonlinear data. It can be used with the regression problem. Output value for the object is computed by the average of k closest neighbors value.

2. Using the KNN example from class, write a function that finds the optimal value for k. You should iterate over a range of values and return the k and the score when the accuracy score is maximized. Be sure to only use odd values.

In [2]:
diabetes_df = pd.read_csv("diabetes.csv")
diabetes_df.head()

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0            6      148             72             35        0  33.6   
1            1       85             66             29        0  26.6   
2            8      183             64              0        0  23.3   
3            1       89             66             23       94  28.1   
4            0      137             40             35      168  43.1   

   DiabetesPedigreeFunction  Age  Outcome  
0                     0.627   50        1  
1                     0.351   31        0  
2                     0.672   32        1  
3                     0.167   21        0  
4                     2.288   33        1

In [57]:
X = diabetes_df.drop('Outcome',axis=1)
y = diabetes_df['Outcome']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

In [54]:
error_rate = []

def k_value():
    for i in range(1,10):
        knn = KNeighborsClassifier(n_neighbors=i)
        knn.fit(X_train, y_train)
        prediction = knn.predict(X_test)
        error_rate.append(np.mean(prediction != y_test))
        #print(error_rate)
        print(confusion_matrix(y_test, prediction))
    print(knn.score(X_test,y_test))

In [55]:
k_value()

[[113  38]
 [ 34  46]]
[[136  15]
 [ 48  32]]
[[108  43]
 [ 32  48]]
[[128  23]
 [ 41  39]]
[[114  37]
 [ 35  45]]
[[124  27]
 [ 42  38]]
[[114  37]
 [ 34  46]]
[[124  27]
 [ 39  41]]
[[115  36]
 [ 33  47]]
0.7012987012987013


3. How did the panel influence your thoughts about working in tech, specifically work in the data realm? Discuss with your group and summarize your thoughts in under 250 words.

* i didn't attended the class but after watching the zoom recording i have learned lot about how the everyone deal with lot of real data and how every thing is correlated to each. Even through we come from different study background. i came from commerce background and changing role to complete different role is bit hard i throght. but after hearing from professionals i found it is also important to known other processes like how business work, how finance flows into business. 